In [ ]:
import sys
!"{sys.executable}" -m pip install numpy matplotlib

In [35]:
import numpy as np

file = "pima-indians-diabetes.data.csv"
data = np.loadtxt(file, delimiter=",")

In [36]:
print("First 5")

print(data[:5])

First 5
[[  6.    148.     72.     35.      0.     33.6     0.627  50.      1.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.      0.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.      1.   ]
 [  1.     89.     66.     23.     94.     28.1     0.167  21.      0.   ]
 [  0.    137.     40.     35.    168.     43.1     2.288  33.      1.   ]]


In [37]:
correlation = np.corrcoef(data, rowvar=False)
np.set_printoptions(precision=3, suppress=True)
print("Correlation Matrix")
print(correlation)

Correlation Matrix
[[ 1.     0.129  0.141 -0.082 -0.074  0.018 -0.034  0.544  0.222]
 [ 0.129  1.     0.153  0.057  0.331  0.221  0.137  0.264  0.467]
 [ 0.141  0.153  1.     0.207  0.089  0.282  0.041  0.24   0.065]
 [-0.082  0.057  0.207  1.     0.437  0.393  0.184 -0.114  0.075]
 [-0.074  0.331  0.089  0.437  1.     0.198  0.185 -0.042  0.131]
 [ 0.018  0.221  0.282  0.393  0.198  1.     0.141  0.036  0.293]
 [-0.034  0.137  0.041  0.184  0.185  0.141  1.     0.034  0.174]
 [ 0.544  0.264  0.24  -0.114 -0.042  0.036  0.034  1.     0.238]
 [ 0.222  0.467  0.065  0.075  0.131  0.293  0.174  0.238  1.   ]]


In [39]:
min_data = np.min(data, axis=0)
max_data = np.max(data, axis=0)

scaled_data = (data - min_data) / (max_data - min_data)
np.set_printoptions(precision=3, suppress=True)

print("first 5 scaled samples")
print(scaled_data[:5])

first 5 scaled samples
[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483 1.   ]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167 0.   ]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183 1.   ]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.    0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2   1.   ]]


In [40]:
scaled_corr = np.corrcoef(scaled_data, rowvar=False)
np.set_printoptions(precision=3, suppress=True)
print("Correlation matrix of rescaled data:")
print(scaled_corr)

Correlation matrix of rescaled data:
[[ 1.     0.129  0.141 -0.082 -0.074  0.018 -0.034  0.544  0.222]
 [ 0.129  1.     0.153  0.057  0.331  0.221  0.137  0.264  0.467]
 [ 0.141  0.153  1.     0.207  0.089  0.282  0.041  0.24   0.065]
 [-0.082  0.057  0.207  1.     0.437  0.393  0.184 -0.114  0.075]
 [-0.074  0.331  0.089  0.437  1.     0.198  0.185 -0.042  0.131]
 [ 0.018  0.221  0.282  0.393  0.198  1.     0.141  0.036  0.293]
 [-0.034  0.137  0.041  0.184  0.185  0.141  1.     0.034  0.174]
 [ 0.544  0.264  0.24  -0.114 -0.042  0.036  0.034  1.     0.238]
 [ 0.222  0.467  0.065  0.075  0.131  0.293  0.174  0.238  1.   ]]
