In [2]:
import numpy as np

file = "pima-indians-diabetes.data.csv"
data = np.loadtxt(file, delimiter=",")

In [4]:
print("First 5")
np.set_printoptions(precision=3, suppress=True)
print(data[:5])

First 5
[[  6.    148.     72.     35.      0.     33.6     0.627  50.      1.   ]
 [  1.     85.     66.     29.      0.     26.6     0.351  31.      0.   ]
 [  8.    183.     64.      0.      0.     23.3     0.672  32.      1.   ]
 [  1.     89.     66.     23.     94.     28.1     0.167  21.      0.   ]
 [  0.    137.     40.     35.    168.     43.1     2.288  33.      1.   ]]


In [5]:
print("TASK 3: Correlation matrix")
corr_whole = np.corrcoef(data, rowvar=False)
print(corr_whole)


TASK 3: Correlation matrix
[[ 1.     0.129  0.141 -0.082 -0.074  0.018 -0.034  0.544  0.222]
 [ 0.129  1.     0.153  0.057  0.331  0.221  0.137  0.264  0.467]
 [ 0.141  0.153  1.     0.207  0.089  0.282  0.041  0.24   0.065]
 [-0.082  0.057  0.207  1.     0.437  0.393  0.184 -0.114  0.075]
 [-0.074  0.331  0.089  0.437  1.     0.198  0.185 -0.042  0.131]
 [ 0.018  0.221  0.282  0.393  0.198  1.     0.141  0.036  0.293]
 [-0.034  0.137  0.041  0.184  0.185  0.141  1.     0.034  0.174]
 [ 0.544  0.264  0.24  -0.114 -0.042  0.036  0.034  1.     0.238]
 [ 0.222  0.467  0.065  0.075  0.131  0.293  0.174  0.238  1.   ]]


In [8]:
print("TASK 4: Rescale to (0,1), print first 5")
data_mix = data.max(axis=0)
data_min = data.min(axis=0)
data_rescaled = (data - data_min) / (data_mix - data_min)

print("TASK 4: First 5 samples after rescaling to (0,1)")
print(data_rescaled[:5])


TASK 4: Rescale to (0,1), print first 5
TASK 4: First 5 samples after rescaling to (0,1)
[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483 1.   ]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167 0.   ]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183 1.   ]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.    0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2   1.   ]]


In [9]:
print("TASK 5: Correlation matrix (rescaled data)")
corr_scaled = np.corrcoef(data_rescaled, rowvar=False)
print(corr_scaled)


TASK 5: Correlation matrix (rescaled data)
[[ 1.     0.129  0.141 -0.082 -0.074  0.018 -0.034  0.544  0.222]
 [ 0.129  1.     0.153  0.057  0.331  0.221  0.137  0.264  0.467]
 [ 0.141  0.153  1.     0.207  0.089  0.282  0.041  0.24   0.065]
 [-0.082  0.057  0.207  1.     0.437  0.393  0.184 -0.114  0.075]
 [-0.074  0.331  0.089  0.437  1.     0.198  0.185 -0.042  0.131]
 [ 0.018  0.221  0.282  0.393  0.198  1.     0.141  0.036  0.293]
 [-0.034  0.137  0.041  0.184  0.185  0.141  1.     0.034  0.174]
 [ 0.544  0.264  0.24  -0.114 -0.042  0.036  0.034  1.     0.238]
 [ 0.222  0.467  0.065  0.075  0.131  0.293  0.174  0.238  1.   ]]


TASK 6: Have correlations changed after rescaling? No, the correlations have not changed after rescaling.
Pearson correlation is scale-invariant. Min-Max scaling is a linear transformation (multiply + add a constant), which preserves the relative distances between values. Therefore all pairwise correlations remain same before and after rescaling.


In [10]:
print("TASK 7: Group sizes ")

class0 = data[data[:, -1] == 0]
class1 = data[data[:, -1] == 1]

print(f"Class 0 (no diabetes): {len(class0)} samples")
print(f"Class 1 (diabetes):    {len(class1)} samples")


TASK 7: Group sizes 
Class 0 (no diabetes): 500 samples
Class 1 (diabetes):    268 samples


In [11]:
print("TASK 8: Correlation matrix for class = 0")
corr_class0 = np.corrcoef(class0, rowvar=False)
print(corr_class0)


TASK 8: Correlation matrix for class = 0
[[ 1.     0.099  0.133 -0.118 -0.132  0.016 -0.08   0.573    nan]
 [ 0.099  1.     0.193  0.016  0.353  0.132  0.096  0.228    nan]
 [ 0.133  0.193  1.     0.187  0.075  0.363  0.027  0.215    nan]
 [-0.118  0.016  0.187  1.     0.413  0.439  0.095 -0.164    nan]
 [-0.132  0.353  0.075  0.413  1.     0.254  0.227 -0.149    nan]
 [ 0.016  0.132  0.363  0.439  0.254  1.     0.071  0.036    nan]
 [-0.08   0.096  0.027  0.095  0.227  0.071  1.     0.042    nan]
 [ 0.573  0.228  0.215 -0.164 -0.149  0.036  0.042  1.       nan]
 [   nan    nan    nan    nan    nan    nan    nan    nan    nan]]


C:\Users\lebna\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\lebna\AppData\Roaming\Python\Python39\site-packages\numpy\lib\_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]


TASK 9: Are class=0 correlations equal to the whole dataset? No, they are not equal. Subsetting to class=0 changes the distribution of samples, so pairwise relationships between features are different from the full dataset. Also, the 'class' column is constant (all 0s) in this group, so its correlation with every other feature is NaN. 

In [12]:
print("TASK 10: Correlation matrix for class = 1")
corr_class1 = np.corrcoef(class1, rowvar=False)
print(corr_class1)


TASK 10: Correlation matrix for class = 1
[[ 1.    -0.055  0.127 -0.079 -0.079 -0.159 -0.069  0.445    nan]
 [-0.055  1.     0.069  0.038  0.261  0.05   0.026  0.099    nan]
 [ 0.127  0.069  1.     0.225  0.089  0.134  0.035  0.263    nan]
 [-0.079  0.038  0.225  1.     0.457  0.312  0.274 -0.092    nan]
 [-0.079  0.261  0.089  0.457  1.     0.055  0.102  0.024    nan]
 [-0.159  0.05   0.134  0.312  0.055  1.     0.137 -0.188    nan]
 [-0.069  0.026  0.035  0.274  0.102  0.137  1.    -0.088    nan]
 [ 0.445  0.099  0.263 -0.092  0.024 -0.188 -0.088  1.       nan]
 [   nan    nan    nan    nan    nan    nan    nan    nan    nan]]


TASK 11: Are correlations for class=0 and class=1 equal? No, they are NOT equal. The two groups represent biologically different populations. Internal relationships along features such as glucose, BMI,
insulin, and age are different between diabetic and non-diabetic patients, showing different metabolic patterns. Aggregate correlations across the whole dataset can mask these within-group structures.
